### ISSUE TITLE
Github Storage Limit

### ISSUE THREAD

**Issue by jasonjabbour** [robotperf/rosbags#3]
I recorded a rosbag while my robot was maneuvering through a simple world for about 1 minute. However, when I try to push the rosbag to GitHub it exceeds the size limit. I'm concerned because this is relatively a very small recording. Have you ran into this issue before?  

![image](https://user-images.githubusercontent.com/55008744/225466242-bfeee154-daeb-470b-ae4e-d277a20bfacd.png)

**Comment by vmayoral** [comment]
@jasonjabbour, this is completely normal if you don't filter out topics and simply record all of them in your simulation.

Your bag is 2.5 GB. See [file limitations in GitHub](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github). You want to stay way below those limits generally.

The general recommendation should be that you should only record the topics that are necessary for your benchmark (and only that, since after all, you can always launch the simulation if you need other aspects). Also a 1 min recording is huge. The others in the repo are a few seconds.
